# Generated by Django 4.0 on 2021-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_points_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
